name: Deploy to Heroku
on:
    push:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: akhileshns/heroku-deploy@v3.4.6
              with:
                heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
                heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
                heroku_email: ${{ secrets.HEROKU_EMAIL }}
                usedocker: true
                docker_build_args: |
                  MLFLOW_TRACKING_URI
                  AWS_ACCESS_KEY_ID
                  AWS_SECRET_ACCESS_KEY
              env:
                MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
                AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

# https://github.com/marketplace/actions/deploy-to-heroku
# Heroku Docker deployment https://devcenter.heroku.com/articles/container-registry-and-runtime