name: Deploy candidate model to prod
on: [issue_comment]

jobs:
  deploy-candidate:
    if: github.event.issue.pull_request != null &&  contains(github.event.comment.body, '/deploy-candidate')
    runs-on: ubuntu-latest
    steps:
      - name: ChatOps For Pull Requests
        uses: machine-learning-apps/actions-chatops@1.41
        with:
          TRIGGER_PHRASE: "/deploy-candidate"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        id: prcomm

      - name: Remove evaluation-started label
        uses: actions-ecosystem/action-remove-labels@v1.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: "evaluation-started"

      - name: Add evaluation-complete label
        uses: actions-ecosystem/action-add-labels@v1.1.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: "evaluation-complete"

      # This step clones the branch of the PR associated with the triggering phrase, but only if it is triggered.
      - name: clone branch of PR
        if: steps.prcomm.outputs.BOOL_TRIGGERED == 'true'
        uses: actions/checkout@v2.3.2
        with:
          ref: ${{ steps.prcomm.outputs.SHA }}

      - uses: actions/checkout@v2

      - name: Set up Python v3.8.5
        uses: actions/setup-python@v2
        with:
          python-version: '3.8.5'

      - name: Set experiment_id
        id: env-var-setter
        run: |
          pip install -r actions_requirements-cli.txt
          echo "::set-output name=EXPERIMENT_ID::`python actions_set_env_variable_in_actions.py EXPERIMENT_ID`"
        env:
          MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI}}

      - name: print output
        run: |
          echo ${{ steps.env-var-setter.outputs.EXPERIMENT_ID }}

      - name: Fetch runs
        uses: alejio/mlflow-tracking-action@v1.1.0
        id: fetch-runs
        with:
          MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
          EXPERIMENT_ID: ${{ steps.env-var-setter.outputs.EXPERIMENT_ID }}
          BASELINE_RUN_QUERY: "tags.live='1'"
          CANDIDATE_RUN_QUERY: "tags.production_candidate='1'"

      - name: Get PR number
        uses: actions/github-script@v3.0.0
        id: get-pr-number
        with:
          script: |
            const {data: pulls} = await github.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              head: '${{ github.event.client_payload.ref }}'
            })
            return pulls[0].number
          result-encoding: string

      - name: Create deploy intent comment
        uses: peter-evans/create-or-update-comment@v1.4.2
        with:
          issue-number: ${{ steps.get-pr-number.outputs.result }}
          body: |
            I'm deploying the candidate model with run ID [${{ steps.fetch-runs.outputs.CANDIDATE_RUNID }}](${{ secrets.MLFLOW_TRACKING_URI }}/#/experiments/${{ steps.fetch-runs.outputs.EXPERIMENT_ID }}/runs/${{ steps.fetch-runs.outputs.CANDIDATE_RUNID }}) to production.
      
      - name: Overwrite MLFlow run tags
        run: |
          python actions_overwrite_tags.py ${{ steps.fetch-runs.outputs.BASELINE_RUNID }} ${{ steps.fetch-runs.outputs.CANDIDATE_RUNID }}
        env:
          MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI}}

      - name: Query deployed model
        id: query-model
        run: |
            echo "::set-output name=CURRENTLY_DEPLOYED_MODEL::`python actions_fetch_currently_deployed_model.py`"
        env:
          MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI}}

      - name: Final comment
        uses: peter-evans/create-or-update-comment@v1.4.2
        with:
            issue-number: ${{ steps.get-pr-number.outputs.result }}
            body: |
                Candidate model deployed to prod! Run ID in production is [${{ steps.query-model.outputs.CURRENTLY_DEPLOYED_MODEL }}](${{ secrets.MLFLOW_TRACKING_URI }}/#/experiments/${{ steps.fetch-runs.outputs.EXPERIMENT_ID }}/runs/${{ steps.query-model.outputs.CURRENTLY_DEPLOYED_MODEL }}).

      - name: Add deployed label
        uses: actions-ecosystem/action-add-labels@v1.1.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: "deployed"